### ISSUE TITLE
code

### ISSUE THREAD

**Issue by YF-SA** [snap-research/MyVLM#1]
Hello author, I was very excited after reading your article. Thank you very much for your contribution. I am now trying to deploy BLIP2 to my task, but I do not know how to improve the official code. I hope to read your code to develop my ideas. I really hope you can upload the relevant code and guidance soon, thank you!

**Comment by yuval-alaluf** [comment]
Hi, I just about finished refactoring the code and I hope we'll get approval to release the code and data shortly, so stay tuned.
