### ISSUE TITLE
The problem with self.values in myvlm_layer.py

### ISSUE THREAD

**Issue by tscvividly** [snap-research/MyVLM#4]
Where does self.values ​​get the image features from? I see in the code that it is directly used as the output and stacked with the output of VLM?

**Comment by yuval-alaluf** [comment]
The `self.values` represents the concept embedding. It does not need to get the image features directly. It is simply a vector that is updated during the optimization process. During training, this vector is always concatenated to the image features and passed to the LLM. The same concatenation happens at inference time, but the vector is fixed.
