### ISSUE TITLE
Request for attention map code.

### ISSUE THREAD

**Issue by tayton42** [snap-research/MyVLM#5]
Thank you for your work. I am very interested in the self-attention maps shown in the paper, but I don't know how to generate them. Could you provide the code to generate the attention maps and indicate where to use it?

**Comment by yuval-alaluf** [comment]
I don't have an organized code, but I can walk you through how to get started and provide you a rough snippet of how we visualized the attention maps. 
First, in the following lines, you'll want to set the `output_attentions` argument to `True` when calling `self.model.generate`. 
https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/vlms/llava_wrapper.py#L64-L79
This should return the per-layer self-attentions in `output.attentions`. 

Next, you'll need to store the index of the concept embedding input to the language model.
This is done via the `concept_token_idxs` that we saved inside the `LlavaLlamaForCausalLM` class:
https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/vlms/llava/model/language_model/llava_llama.py#L123-L133
You'll probably want to store it and return it in the `generate()` function as well, using a similar approach.

Once you have that, you can visualize the embedding using something like:
```python
path = 'visualization.jpg'
concept_token_idxs = output.concept_token_idxs
for attn_idx, attention_probs in enumerate(output.attentions):
    for sample_idx in range(batch_size):
        concept_idx = concept_token_idxs[sample_idx][0]
        sample_attention = attention_probs[sample_idx, :, concept_idx, concept_idx - 576: concept_idx].cpu()
        avg_sample_attention = torch.mean(sample_attention, dim=0)
        attention_as_image = avg_sample_attention.reshape((24, 24)).cpu()
        plt.imshow(attention_as_image.detach().cpu()).figure.savefig(path)
        torch.save(attention_as_image, path.replace('.jpg', '.pt'))
```
Again, I haven't tested this code after the refactor I did before publishing, so this will most likely not work as is, but I hope this helps you understand the process.
Hope this helps!

**Comment by tayton42** [comment]
> I don't have an organized code, but I can walk you through how to get started and provide you a rough snippet of how we visualized the attention maps. First, in the following lines, you'll want to set the `output_attentions` argument to `True` when calling `self.model.generate`.
> 
> https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/vlms/llava_wrapper.py#L64-L79
> 
> 
> This should return the per-layer self-attentions in `output.attentions`.
> Next, you'll need to store the index of the concept embedding input to the language model. This is done via the `concept_token_idxs` that we saved inside the `LlavaLlamaForCausalLM` class:
> 
> https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/vlms/llava/model/language_model/llava_llama.py#L123-L133
> 
> 
> You'll probably want to store it and return it in the `generate()` function as well, using a similar approach.
> Once you have that, you can visualize the embedding using something like:
> 
> ```python
> path = 'visualization.jpg'
> concept_token_idxs = output.concept_token_idxs
> for attn_idx, attention_probs in enumerate(output.attentions):
>     for sample_idx in range(batch_size):
>         concept_idx = concept_token_idxs[sample_idx][0]
>         sample_attention = attention_probs[sample_idx, :, concept_idx, concept_idx - 576: concept_idx].cpu()
>         avg_sample_attention = torch.mean(sample_attention, dim=0)
>         attention_as_image = avg_sample_attention.reshape((24, 24)).cpu()
>         plt.imshow(attention_as_image.detach().cpu()).figure.savefig(path)
>         torch.save(attention_as_image, path.replace('.jpg', '.pt'))
> ```
> 
> Again, I haven't tested this code after the refactor I did before publishing, so this will most likely not work as is, but I hope this helps you understand the process. Hope this helps!

Thank you for your response, it is really helpful to me.
