### ISSUE TITLE
Clarification on Inference and Test Data for Reproducing Results

### ISSUE THREAD

**Issue by IemProg** [snap-research/MyVLM#8]
Hi @yuval-alaluf ,

First of all, thank you for sharing such an interesting paper and publishing such clean code—it’s really appreciated!

I have been exploring your repository and trying to replicate the results of the paper. However, I encountered some challenges related to the inference process and test data. Specifically:

**Inference Clarification:** While there is some documentation on inference, it is not entirely clear how to execute the inference step properly to reproduce the results mentioned in the paper, especially the personalized captioning and VQA tasks. Could you provide detailed instructions or a script on how to run inference to evaluate model performance on test data?

**Test Data Availability:** I noticed that the data folder does not seem to contain any test samples. Could you please clarify where to find the testing samples that were used in the paper's experiments, or provide additional information on how to generate or obtain them?

It would be really helpful to have more concrete guidance on these points to ensure accurate replication of your results.

Thanks again for your work and for making this available!

**Comment by yuval-alaluf** [comment]
The test data is available via [HuggingFace](https://huggingface.co/datasets/yuvalalaluf/MyVLM). There you can find all the objects that we used in the paper. We will not release the images of the individuals present in the paper as this is a bit more sensitive.
Regarding the inference, the README provides [detailed explanations](https://github.com/snap-research/MyVLM?tab=readme-ov-file#inference) of how to run each of the models. We have also released all concept heads and concept embeddings for reproducibility. What information are you missing?

**Comment by passing2961** [comment]
Hi,

In the paper, the authors collected 350 images of objects and 330 images of people for the evaluation dataset. For clarification, the test data available via Hugging Face includes only the object images, presumably because including images of people could raise privacy concerns. Is my understanding correct?

Thanks for your great work :)

**Comment by yuval-alaluf** [comment]
That is correct. We're only releasing the object images because of the sensitivity of releasing images of individuals.
